/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jans_cedarling_bridge_Cedarling */

#ifndef _Included_io_jans_cedarling_bridge_Cedarling
#define _Included_io_jans_cedarling_bridge_Cedarling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jans_cedarling_bridge_Cedarling
 * Method:    initJniCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_jans_cedarling_bridge_Cedarling_initJniCache
  (JNIEnv *, jclass);

/*
 * Class:     io_jans_cedarling_bridge_Cedarling
 * Method:    authorize
 * Signature: (Lio/jans/cedarling/bridge/authz/AuthorizeRequest;)Lio/jans/cedarling/bridge/authz/AuthorizeResult;
 */
JNIEXPORT jobject JNICALL Java_io_jans_cedarling_bridge_Cedarling_authorize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jans_cedarling_bridge_Cedarling
 * Method:    authorizeUnsigned
 * Signature: (Lio/jans/cedarling/bridge/authz/AuthorizeRequestUnsigned;)Lio/jans/cedarling/bridge/authz/AuthorizeResult;
 */
JNIEXPORT jobject JNICALL Java_io_jans_cedarling_bridge_Cedarling_authorizeUnsigned
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jans_cedarling_bridge_Cedarling
 * Method:    createNativeCedarling
 * Signature: (Lio/jans/cedarling/bridge/config/BootstrapConfiguration;)V
 */
JNIEXPORT void JNICALL Java_io_jans_cedarling_bridge_Cedarling_createNativeCedarling
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jans_cedarling_bridge_Cedarling
 * Method:    cleanupCedarling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_jans_cedarling_bridge_Cedarling_cleanupCedarling
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
